### PR TITLE
Support multiple CUDA versions

### LINKED ISSUE #30: The found PyTorch version is too old
Hi, @pmeier. Thanks for this package, it looks very useful. I've always wanted something like this.

I am on Linux, NVIDIA driver 430.50. According to [Table 1 here](https://docs.nvidia.com/deploy/cuda-compatibility/index.html), the latest CUDA version I can install is 10.1. When I ran `ltt install torch`, I expected it to run

```
pip install torch==1.8.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
```

i.e., the latest PyTorch version that supports 10.1 (as far as I know), but it does 

```
Collecting torch==1.4.0+cu100
  Downloading https://download.pytorch.org/whl/cu100/torch-1.4.0%2Bcu100-cp36-cp36m-linux_x86_64.whl (723.9 MB)
     |██▏                             | 50.2 MB 43.4 MB/s eta 0:00:16^C
```

which I killed. It looks like instead of installing 1.8.0 with CUDA 10.1, it installs 1.4.0 with CUDA 10.0. Is this expected?

### PR DESCRIPTION
**Pull request by pmeier**
Fixes #30. In #31 support for installing PyTorch for the latest CUDA version the driver supports was added. With this PR `light-the-torch` now supports installing PyTorch with all versions supported by the driver.

### CODE REVIEW

**Comment by pmeier** [comment]
@fepegar could you run your use case against this branch with `pip install git+https://github.com/pmeier/light-the-torch@support-multiple-cudas`? With that you should now be able to install wheels for all supported CUDA versions. In your case `ltt install "torch<1.3"` should fall back to CUDA 10.0. Is that correct?

If yes, I'm going to merge this and push a release.

**Comment by fepegar** [comment]
> should fall back to CUDA 10.0. Is that correct?

It didn't. It tried the CPU version.

This is what I got.

```shell
$ ltt install "torch<1.3"                                                                         

Collecting torch==1.2.0+cpu
  Downloading https://download.pytorch.org/whl/cpu/torch-1.2.0%2Bcpu-cp36-cp36m-manylinux1_x86_64.whl (103.9 MB)
     |████████████████████████████████| 103.9 MB 79 kB/s 
Collecting numpy
  Using cached numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
Installing collected packages: numpy, torch
Successfully installed numpy-1.19.5 torch-1.2.0+cpu
WARNING: You are using pip version 20.2.4; however, version 21.1.2 is available.
You should consider upgrading via the '/home/fernando/miniconda3/envs/test/bin/python -m pip install --upgrade pip' command.
/bin/sh: 1: cannot open 1.3: No such file
Traceback (most recent call last):
  File "/home/fernando/miniconda3/envs/test/bin/ltt", line 8, in <module>
    sys.exit(main())
  File "/home/fernando/miniconda3/envs/test/lib/python3.6/site-packages/light_the_torch/cli/__init__.py", line 19, in main
    cmd.run(pip_install_args)
  File "/home/fernando/miniconda3/envs/test/lib/python3.6/site-packages/light_the_torch/cli/commands.py", line 23, in run
    self._run(pip_install_args)
  File "/home/fernando/miniconda3/envs/test/lib/python3.6/site-packages/light_the_torch/cli/commands.py", line 110, in _run
    subprocess.check_call(cmd, shell=True)
  File "/home/fernando/miniconda3/envs/test/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python -m pip install torch<1.3' returned non-zero exit status 2.
```

Then I ran these:

```shell
$ python -m pip install torch<1.3                                                                      
zsh: no such file or directory: 1.3
$ python -m pip install "torch<1.3"                                                                       
Requirement already satisfied: torch<1.3 in ./miniconda3/envs/test/lib/python3.6/site-packages (1.2.0+cpu)
Requirement already satisfied: numpy in ./miniconda3/envs/test/lib/python3.6/site-packages (from torch<1.3) (1.19.5)
WARNING: You are using pip version 20.2.4; however, version 21.1.2 is available.
You should consider upgrading via the '/home/fernando/miniconda3/envs/test/bin/python -m pip install --upgrade pip' command.
```

**Comment by pmeier** [comment]
@fepegar Thanks for trying. Indeed the ordering was buggy and it was not tested properly. Should be fixed now. Could you retry?

**Comment by fepegar** [comment]
Success!

```python
$ ltt install "torch<1.3"                                                                                                                  ✔  08:46:46
Collecting torch==1.2.0
  Downloading https://download.pytorch.org/whl/cu100/torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (748.8 MB)
     |███████████▏                    | 260.2 MB 12.0 MB/s eta 0:00:41^C
```

**Comment by pmeier** [comment]
Just to make sure `ltt install torch` still gives you `torch==1.8.1`, correct?

**Comment by fepegar** [comment]
Oops, no:

```shell
$ ltt install torch
Collecting torch==1.9.0+cpu
  Downloading https://download.pytorch.org/whl/cpu/torch-1.9.0%2Bcpu-cp36-cp36m-linux_x86_64.whl (175.5 MB)
     |█████████████▊                  | 75.4 MB 38.6 MB/s eta 0:00:03^C
```

**Comment by pmeier** [comment]
Argh. Let me look into that ...

**Comment by fepegar** [comment]
Looking good.

```shell
$ ltt install torch
Collecting torch==1.8.1+cu101
  Using cached https://download.pytorch.org/whl/cu101/torch-1.8.1%2Bcu101-cp36-cp36m-linux_x86_64.whl (763.6 MB)
```

```shell
$ ltt install "torch<1.3"
Collecting torch==1.2.0
  Downloading https://download.pytorch.org/whl/cu100/torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (748.8 MB)
```

**Comment by pmeier** [comment]
What happened was that the version of the package was prioritized over the computation backend. Thus, `(1.9.0, cpu) > (1.8.1, cu101)`. By reversing it, you now get the intended behavior.

**Comment by fepegar** [comment]
I see. Yes, I think it's better this way. Good job!

**Pull request merged**
